'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


def solution():
    result = result2 = 0
    i = 1
    last = last2 = 1
    while i < 4000000:
        i = last + last2
        if i % 2 == 0:
            result += i
        last2 = last
        last = i

    x, y = 0, 1
    while y < 4000000:
        x, y = y, x + y
        if y % 2 == 0:
            result2 += y

    print(result)
    print(result2)


solution()
