'''

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

'''


def solution():
    def triangle(n):
        return n*(n+1)//2

    def pentagonal(n):
        return n*(3*n-1)//2

    def hexagonal(n):
        return n*(2*n-1)

    def gen_pentagonal():
        return {pentagonal(x) for x in range(1000000)}

    def gen_hexagonal():
        return {hexagonal(x) for x in range(1000000)}

    hexagonals = gen_hexagonal()
    pentagonals = gen_pentagonal()
    print(pentagonals.intersection(hexagonals))


if __name__ == '__main__':
    solution()
